version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ArtemPotapov52"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # None currently
